"""
Tests for sharp_expr()'s "=" to "==" conversion -- a real, high-impact
bug: the original re.sub('=', '==', expr) doubled every "=" character
indiscriminately, including ones already part of a real, multi-
character comparison operator (<=, >=, ==, !=), mangling them into
invalid Python syntax: "<=" became "<==", ">=" became ">==", "=="
became "====", "!=" became "!==". Only the two single-character
comparisons (<, >) were ever unaffected, which is what first made the
"=" substitution the suspect once #expr's own AST evaluator was
already confirmed working for simple and/or expressions.

Real-world impact confirmed to be substantial, not theoretical: a
single real article (ur.wikipedia.org's pnb equivalent -- Special:
Export of pnb.wikipedia.org's "اسٹریلیا" article, with templates
included) hit this 6363 times in one page alone, via the citation/CS1
and Wikidata module machinery its infobox pulls in, both of which
lean heavily on #expr comparisons for their own internal logic. Fixed
by only converting a standalone "=" -- one not already preceded or
followed by a character that would make it part of an existing
multi-character comparison operator.

Run with:
    python -m unittest tests.test_sharp_expr_equals_operator -v
or, from the tests/ directory:
    python -m unittest test_sharp_expr_equals_operator -v
"""

import sys
import unittest

sys.path.insert(0, '..')  # allow running directly from tests/ without installing

import wikiextractor.extract as ex


class StandaloneEqualsConversionTests(unittest.TestCase):
    """MediaWiki's own #expr syntax uses a single "=" for equality
    (not Python's "=="), so a bare "=" still needs converting -- the
    fix must not remove this, only stop over-applying it.
    """

    def test_standalone_equals_still_converts_to_double_equals(self):
        self.assertEqual(ex.sharp_expr('3 = 3'), '1')
        self.assertEqual(ex.sharp_expr('3 = 2'), '0')

    def test_standalone_equals_with_no_spaces(self):
        self.assertEqual(ex.sharp_expr('3=3'), '1')


class MultiCharacterComparisonOperatorTests(unittest.TestCase):
    """The actual bug: each of these used to mangle into invalid
    Python syntax and fail entirely. Confirmed directly, one at a
    time, against the real, broken behavior before writing the fix.
    """

    def test_less_than_or_equal(self):
        self.assertEqual(ex.sharp_expr('3 <= 2'), '0')
        self.assertEqual(ex.sharp_expr('2 <= 3'), '1')
        self.assertEqual(ex.sharp_expr('3 <= 3'), '1')

    def test_greater_than_or_equal(self):
        self.assertEqual(ex.sharp_expr('3 >= 2'), '1')
        self.assertEqual(ex.sharp_expr('2 >= 3'), '0')
        self.assertEqual(ex.sharp_expr('3 >= 3'), '1')

    def test_double_equals(self):
        self.assertEqual(ex.sharp_expr('3 == 3'), '1')
        self.assertEqual(ex.sharp_expr('3 == 2'), '0')

    def test_not_equals(self):
        self.assertEqual(ex.sharp_expr('3 != 2'), '1')
        self.assertEqual(ex.sharp_expr('3 != 3'), '0')

    def test_operators_with_no_spaces(self):
        self.assertEqual(ex.sharp_expr('3<=3'), '1')
        self.assertEqual(ex.sharp_expr('3>=3'), '1')
        self.assertEqual(ex.sharp_expr('3==3'), '1')
        self.assertEqual(ex.sharp_expr('3!=3'), '0')

    def test_single_character_comparisons_still_work(self):
        # These were never broken -- confirming the fix didn't
        # regress the ones that already worked.
        self.assertEqual(ex.sharp_expr('3 > 2'), '1')
        self.assertEqual(ex.sharp_expr('3 < 2'), '0')


class RealWorldExpressionShapeTests(unittest.TestCase):
    """The literal, real expression shapes confirmed failing in a
    real article (pnb.wikipedia.org's "اسٹریلیا") before this fix --
    generated by citation/CS1 and Wikidata module machinery doing
    #expr-based loop/comparison logic.
    """

    def test_the_exact_failing_expression_from_the_real_article(self):
        self.assertEqual(ex.sharp_expr('1 < 99 and 1 + 0 >= 99'), '0')

    def test_combined_comparisons_with_and(self):
        self.assertEqual(ex.sharp_expr('1 < 5 and 1 >= 1'), '1')
        self.assertEqual(ex.sharp_expr('1 < 5 and 1 >= 5'), '0')

    def test_combined_comparisons_with_or(self):
        self.assertEqual(ex.sharp_expr('1 <= 0 or 1 >= 1'), '1')


class RealPipelineEndToEndTests(unittest.TestCase):
    """Not sharp_expr() directly -- the real chain (clean_text() ->
    expandTemplate() -> callParserFunction()), confirming a template
    that relies on these operators for its own conditional logic now
    resolves correctly instead of leaving a malformed-expression
    error span in the output.
    """

    def test_real_pipeline_template_using_range_check(self):
        templates = {
            'Template:InRange': '{{#ifexpr: {{{1}}} >= 10 and {{{1}}} <= 20 | in range | out of range }}',
        }
        extractor = ex.Extractor(1, "1", "https://x", "Test Article", [], templates=templates,
                                  templatePrefix='Template:')
        result = extractor.clean_text('{{InRange|15}}', expand_templates=True)
        self.assertIn('in range', '\n'.join(result))

        result2 = extractor.clean_text('{{InRange|5}}', expand_templates=True)
        self.assertIn('out of range', '\n'.join(result2))


if __name__ == '__main__':
    unittest.main()
